config/routes.rb
Rails.application.routes.draw do

  namespace :api, defaults: { format: :json} do
    namespace :v1 do
      resources :urls
    end
  end

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}

  #devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
   root to: 'urls#new'
   resources :urls, only: [:new, :create,:index]

   resources :users
end

app/models/url.rb
class Url < ActiveRecord::Base

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :login
  enum role: [:user, :web_service_user, :admin]
  after_initialize :set_default_role, :if => :new_record?


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,:omniauthable, authentication_keys: [:login]

  validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true
  validates :username, presence: :true, uniqueness: {case_sensitive: false}

  validate :validate_username


  def validate_username
    if User.where(email: username).exists?
      errors.add(:username, :invalid)
    end
  end

  def self.find_for_google_oauth2(access_token, signed_in_resource=nil)
    data = access_token.info
    user = User.where(:provider => access_token.provider, :uid => access_token.uid ).first
    if user
      return user
    else
      registered_user = User.where(:email => access_token.info.email).first
      if registered_user
        return registered_user
      else
        user = User.create(name: data["name"],
                           provider:access_token.provider,
                           email: data["email"],
                           uid: access_token.uid ,
                           password: Devise.friendly_token[0,20],
        )
      end
    end
  end

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", {:value => login.downcase}]).first
    else
      if conditions[:username].nil?
        where(conditions).first
      else
        where(username: conditions[:username]).first
      end
    end
  end

  def login=(login)
    @login = login
  end

  def login
    @login || self.username || self.email
  end

  def set_default_role
    self.role ||= :user
  end

  def self.from_omniauth(auth)
    find_by_provider_and_uid(auth["provider"], auth["uid"]) || create_with_omniauth(auth)
  end

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
    end
  end

end

app/controllers/api/v1/urls_controller.rb
module Api
  module V1
    class UrlsController < ApplicationController

      http_basic_authenticate_with name: USERNAME, password: PASSWORD, only: [:index,:create]

     # curl -u "username:password" http://localhost:3000/api/v1/urls
      def index
        @urls = Url.all.collect{|a| [a.main_url,a.shortener_url]}
        data = []
        data << @urls
        render json: data
      end

      #curl -u "username:password" -d "url=URL"  http://localhost:3000/api/v1/urls
      def create
        if params[:url]
          client = Bitly.client
          @url = client.shorten(params[:url])
          @urls = Url.create(main_url: @url.long_url ,shortener_url: @url.short_url) if @url
        end
        render json: @urls
      end

    end
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end


end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    @user = User.find_for_google_oauth2(request.env["omniauth.auth"], current_user)
    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.google_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
  end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController

  def index
   @urls = Url.all
  end

  def new
  end

  def create
    if !params[:url].blank? and user_signed_in?
      client = Bitly.client
      @url = client.shorten(params[:url])
      Url.create(main_url: @url.long_url ,shortener_url: @url.short_url) if @url
      redirect_to :action => 'index'
    else
      flash[:notice] = "Please login and create the url shortener."
      render :action => 'new'
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  respond_to :json
  before_action :authenticate_user!
  after_action :verify_authorized

  def index
    @users = User.all
    authorize User
  end

  def show
    @user = User.find(params[:id])
    authorize @user
  end

  def update
    @user = User.find(params[:id])
    authorize @user
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    authorize user
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def secure_params
    params.require(:user).permit(:role)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-dismissible alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
    <li><%= link_to "My Account", edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <% if user_signed_in? %>
        <%= link_to 'Url Shortener', root_path, class: 'navbar-brand' %>
      <%end%>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
         <li><%= link_to "Url Lists", urls_path %></li>
        <%end%>
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Url Shortener" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails Devise Pundit" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/urls/index.html.erb
<div class="container">
  <div class="row">
    <h3>Url Lists</h3>
    <div class="column">
      <table class="table">
        <tbody>
        <% @urls.each do |url| %>
            <tr>
              <td class="main_url">
              <%= url.main_url %><br /><br />
            </td>
            <td>
              <%= link_to url.shortener_url, url.shortener_url, target: "_blank" %><br /><br />
            </td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<%= link_to "Create another Url", root_path , :class => "url_button"%>

app/views/urls/new.html.erb
<%= flash[:notice]%>
<h1>Create a new URL Shortener:</h1>

<%= form_for "", url: urls_path, method: :post do |f| %>
 <%= f.text_field :url %>
 <%= f.submit "Url Shortener" %>
<% end %>

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>